### ISSUE TITLE
observatory list

### ISSUE THREAD

**Issue by j-faria** [j-faria/caniobserveit#2]
In the 'where' search box, I want to search for (and find the right thing...)

- [ ] vlt
- [ ] paranal
- [ ] ut1, ut2, ...
- [x] la silla
- [ ] ohp
- [ ] harps
- [ ] eso (should display all ESO sites)
- [ ] *what else?*

**Comment by DanielAndreasen** [comment]
You mean you will be able to search for all instruments, sites, telescopes (etc.)?
I guess we can use the [awesomplete](https://github.com/LeaVerou/awesomplete) package you have prepared.

**Comment by DanielAndreasen** [comment]
This should be fixed with PR #3

**Comment by DanielAndreasen** [comment]
At least the observatories are shown which are in the `data/observatories.txt`
